// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXKksE5BEJA4idDGCxaxsf1SNH6_YUCCs',
    appId: '1:245005786812:web:3156bb6c2e579290c9bab9',
    messagingSenderId: '245005786812',
    projectId: 'pysch-project',
    authDomain: 'pysch-project.firebaseapp.com',
    storageBucket: 'pysch-project.firebasestorage.app',
    measurementId: 'G-EJY24FQKW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJm353pFLXOj_803xiSZKgwKUWbgQyvMY',
    appId: '1:245005786812:android:a71828b20e85b4e9c9bab9',
    messagingSenderId: '245005786812',
    projectId: 'pysch-project',
    storageBucket: 'pysch-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZryHTHuVentShDaBxfLSLguCyGKx_IKU',
    appId: '1:245005786812:ios:d38e1ae5f8e09f34c9bab9',
    messagingSenderId: '245005786812',
    projectId: 'pysch-project',
    storageBucket: 'pysch-project.firebasestorage.app',
    iosBundleId: 'com.example.psychProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZryHTHuVentShDaBxfLSLguCyGKx_IKU',
    appId: '1:245005786812:ios:d38e1ae5f8e09f34c9bab9',
    messagingSenderId: '245005786812',
    projectId: 'pysch-project',
    storageBucket: 'pysch-project.firebasestorage.app',
    iosBundleId: 'com.example.psychProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXKksE5BEJA4idDGCxaxsf1SNH6_YUCCs',
    appId: '1:245005786812:web:300c4b82b898a48bc9bab9',
    messagingSenderId: '245005786812',
    projectId: 'pysch-project',
    authDomain: 'pysch-project.firebaseapp.com',
    storageBucket: 'pysch-project.firebasestorage.app',
    measurementId: 'G-JLVP4BEWZF',
  );
}
